[project]
name = "visa-mcp"
version = "0.1.0"
description = "VISA based oscilloscope control through MCP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pyvisa>=1.15.0",
    "pyvisa-py>=0.8.0",
]
